import { SelectedSpots, Spot } from "@/types";

const generateSelectedSpot = (selectedSpot?: Spot): SelectedSpots => {
  let spots: SelectedSpots = {
    spot8a: false,
    spot8b: false,
    spot8c: false,
    spot8d: false,
    spot8e: false,
    spot8f: false,
    spot8g: false,
    spot8h: false,
    spot7a: false,
    spot7b: false,
    spot7c: false,
    spot7d: false,
    spot7e: false,
    spot7f: false,
    spot7g: false,
    spot7h: false,
    spot6a: false,
    spot6b: false,
    spot6c: false,
    spot6d: false,
    spot6e: false,
    spot6f: false,
    spot6g: false,
    spot6h: false,
    spot5a: false,
    spot5b: false,
    spot5c: false,
    spot5d: false,
    spot5e: false,
    spot5f: false,
    spot5g: false,
    spot5h: false,
    spot4a: false,
    spot4b: false,
    spot4c: false,
    spot4d: false,
    spot4e: false,
    spot4f: false,
    spot4g: false,
    spot4h: false,
    spot3a: false,
    spot3b: false,
    spot3c: false,
    spot3d: false,
    spot3e: false,
    spot3f: false,
    spot3g: false,
    spot3h: false,
    spot2a: false,
    spot2b: false,
    spot2c: false,
    spot2d: false,
    spot2e: false,
    spot2f: false,
    spot2g: false,
    spot2h: false,
    spot1a: false,
    spot1b: false,
    spot1c: false,
    spot1d: false,
    spot1e: false,
    spot1f: false,
    spot1g: false,
    spot1h: false,
  };

  if (selectedSpot) {
    spots[selectedSpot] = true;
  }

  return spots;
};

export default generateSelectedSpot;
