import Game from "@/components/Game/Game";
import { Box } from "@mui/material";
import Head from "next/head";

const Home = () => {
  return (
    <>
      <Head>
        <title>Chess!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Game />
    </>
  );
};

export default Home;
